### ISSUE TITLE
getting 404 on cds/aspects-inheritance 

### ISSUE THREAD

**Issue by Muhtasham** [cap-js/docs#1425]
getting 404 on cds/aspects-inheritance

https://github.com/cap-js/docs/blob/692f45ba7867af90c0d72185f7ffa301e4197140/cds/aspects-inheritance

is this repo not live version of https://cap.cloud.sap/docs/cds ? Is there any central resource to pull in latest docs?

**Comment by renejeglinsky** [comment]
Hi @Muhtasham ,

what you can see on cap.cloud.sap is a mix of two repositories, as we do have this open source repository here but an internal repository as well. So in your case the topic is in the internal repository. That's why you can't find it here or edit it.

Do you have any feedback for that specific topic you want to share?

**Comment by Muhtasham** [comment]
> Do you have any feedback for that specific topic you want to share?

Yes would be nice to have PDF version of whole documentation too :)

**Comment by renejeglinsky** [comment]
Providing a PDF is not planned at this point in time. Anyway thanks for opening the issue and engaging with us :)
