### ISSUE TITLE
Navigation by anchor seems to be off

### ISSUE THREAD

**Issue by njames** [cap-js/docs#472]
This is probably a vitescript issues but when I navigate to an anchor 

eg https://cap.cloud.sap/docs/get-started/in-a-nutshell#vue

the page doesn't seem to land at that anchor properly. 

Sometimes it seems to be at the bottom of the page and sometimes just under the header at the top. 

If I discover more about the behaviour I will add to this but as I said not sure if it is a vitepress issue or this repo?

(Ahha - if I dismiss the survey notice at the top it seems to be better.)

**Comment by chgeo** [comment]
We are aware of this issue.  The behavior is caused by 
- The header offset which Vitepress doesn't take into account properly. I still need to report this.
- Our Node/Java toggle which manipulates the DOM through JS.  This interfered with Vitepress' calculation of the scroll position.  We have changed this to CSS.  The fix is going to be available with the upcoming release next week.

**Comment by renejeglinsky** [comment]
Hi Nigel,

The fix is now publicly available.

Thanks,
René
