### ISSUE TITLE
Explain mta.yaml from top to bottom

### ISSUE THREAD

**Issue by njames** [cap-js/docs#482]
Dear CAP Team,
I really like the premise of CAP - just a couple of easy command and away you go. 

The problem is that you are learning another language of yaml and these command are magically adding things and it isn't always clear what has been added. 

I think a very good addition to the documentation would be to explain all the magic files (mta.yaml, ui5.yaml etc) from top to bottom to explain what each bit does. 

And it would be nice if the different tools didn't clobber your mta.yaml 

Trying use the `fiori` cli tool explained [here](https://developers.sap.com/tutorials/btp-app-work-zone-setup.html) was complaining about a misformed mta.yaml without saying what was misformed then I find that app-db was missing so I rerun `cds add hana --for production` and that obliterates my xsuaa section from the yaml. 

😱 

sincerely, 
Frustrated

**Comment by njames** [comment]
This is slightly instructive. 

https://github.com/SAP-samples/cloud-cap-risk-management/blob/cap-mta-deployment/mta.yaml

Could the tooling add comments?

**Comment by swaldmann** [comment]
Hi @njames,

First of all, thanks for your continuous feedback!

> I think a very good addition to the documentation would be to explain all the magic files (mta.yaml, ui5.yaml etc) from top to bottom to explain what each bit does.

`mta.yaml` and `ui5.yaml` are not CAP products, so we usually leave detailed explanations of their general structure to MTA build tool and UI5 documentation. I understand your intuition to add those explanations to CAPire though, as our documentation is increasingly seen as a holistic guidance covering all of your development process. We'll discuss some steps we can do in our CAPire sync. 

For the `cds add` commands specifically, I think a code box like
```sh
cds add hana --for production
```
with a line-by-line explanation of changes would be a good middle ground. What do you think?

> so I rerun cds add hana --for production and that obliterates my xsuaa section from the yaml

Can you please provide the prior `mta.yaml`? I can't reproduce the XSUAA section being removed. `cds add` is purely additive bar very few exceptions.

Note that some whitespace changes are not preventable, as we're merging the abstract syntax tree (AST) instead of the concrete syntax tree (CST). Popular tools like `npm` are doing the same approach, for example, when you modify your `package.json` via `npm add` the file might be re-indented. This shouldn't compromise the functionality of the modified file, though.

> Could the tooling add comments? Perhaps if there was a comments on flag --comments

We made the decision that a clean, minimal and straightforward configuration is preferred over excessive ornamentation via comments (e.g. the `# -------------------- SIDECAR MODULE ------------------------`-like fences in your example), therefore `cds add mta` just adds comments sparsely.

Best regards,
Steffen

**Comment by njames** [comment]
Thanks Steffen, 

I appreciate you all putting up with my "feedback" :)

I understand thought about the comments.

I think the combination of the other tools: `fiori`, `ui5` and `cds` did the trick with elements disappearing from the mta.yml

I will try and reproduce that as I work on other things and if I can reliably reproduce it I will document the steps taken to get there. 

Cheers, 
Nigel

**Comment by njames** [comment]
I have found some other good sources:

+ https://blogs.sap.com/2020/11/18/multi-target-application-model-mta-sap-cloud-platform-cloud-foundry/
+ https://www.sap.com/documents/2016/06/e2f618e4-757c-0010-82c7-eda71af511fa.html
+ https://sap.github.io/cloud-mta-build-tool/configuration/

**Comment by njames** [comment]
and with that I will call this closed
