### ISSUE TITLE
Java | Remote Services | Using BTP Destinations | Sample code is outdated 

### ISSUE THREAD

**Issue by dinurp** [cap-js/docs#815]
The following sample code in [Java | Remote Services | Using BTP Destinations](https://cap.cloud.sap/docs/java/cqn-services/remote-services#using-btp-destinations) is for [SAP Cloud SDK v4](https://sap.github.io/cloud-sdk/docs/java/v4/features/connectivity/http-client)
```
HttpDestination destination = DestinationAccessor.getDestination("destinationName").asHttp();
HttpClient httpClient = HttpClientAccessor.getHttpClient(destination);
```
With  current [SAP Cloud SDK (v4)](https://sap.github.io/cloud-sdk/docs/java/v4/features/connectivity/http-client) sample code for the same is:
```
Destination destination = DestinationAccessor.getDestination("my-destination");
HttpClient client = HttpClientAccessor.getHttpClient(destination);
```

I don't think the old sample code is in error now. It is just that [some are pointing out](https://community.sap.com/t5/technology-q-a/cap-java-destination-proxy-configuration/qaq-p/13662392) the older sample here as **the** correct way. It would be good to have consistent documentation on used libraries.

**Comment by renejeglinsky** [comment]
Hi Dinurp,
we appreciate your effort and contributions to capire. I'll involve my colleagues with a deeper knowledge in this area.
All the best,
René

**Comment by beckermarc** [comment]
Thanks for pointing that out. I think in your second example you actually wanted to link to Cloud SDK v5 docs here: https://sap.github.io/cloud-sdk/docs/java/features/connectivity/http-client, right?

Currently CAP Java is fully compatible with Cloud SDK 5, but still uses Cloud SDK 4 by default. Apps have to explicitly switch to Cloud SDK 5 when using CAP. This is due to some of the incompatible changes from Cloud SDK 4 to Cloud SDK 5. CAP will only increase the new minimum version of Cloud SDK to some 5.x version with our next CAP Java major release 3.x somewhen in the middle of this year.

Due to this I prefer to keep our documentation Cloud SDK 4 compatible. The example in our docs works for both 4 and 5 of Cloud SDK. However if we would change the example code now, this might irritate users still using Cloud SDK 4.

You can find the minimum versions of dependencies for CAP Java also documented here: https://cap.cloud.sap/docs/java/versions#minimum-versions

**Comment by dinurp** [comment]
Thanks @beckermarc.
Yes. I meant to link to Cloud SDK  v5 but linked to Cloud SDK v4 instead.
If CAP is still working with v4 out of the box, then you are right have the sample based on v4.

**Comment by beckermarc** [comment]
After talking to @renejeglinsky we decided to add a code-group for this to the docs, allowing you to toggle between a version for Cloud SDK v4 and v5: https://github.com/cap-js/docs/pull/834

**Comment by renejeglinsky** [comment]
Thanks @dinurp and @beckermarc !
